version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./package.json:/usr/app/package.json
      - ./src/:/usr/app/src
    ports:
      - 3000:3000
    restart: always
