version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./package.json:/app/package.json
      - ./src/:/app/src
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always
