const actionTypeConstants = {
  GET_SEARCH_RESULTS: "GET_SEARCH_RESULTS",
  SELECT_ITEM_WITH_ID: "SELECT_ITEM_WITH_ID",
  UPDATE_SEARCH_RESULTS: "UPDATE_SEARCH_RESULTS",
  UPDATE_SEARCH_TERM: "UPDATE_SEARCH_TERM"
};

export default actionTypeConstants;
