export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const RESET_SEARCH_RESULTS = "RESET_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
export const SEARCH_RESULTS_LOADED = "SEARCH_RESULTS_LOADED";
export const SEARCH_RESULTS_API_ERRORED = "SEARCH_RESULTS_API_ERRORED";
