export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const RESET_SEARCH_RESULTS = "RESET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS_SUCCESS = "GET_SEARCH_RESULTS_SUCCESS";
export const GET_SEARCH_RESULTS_FAILURE = "GET_SEARCH_RESULTS_FAILURE";
export const SET_SORTED_SEARCH_RESULTS = "SET_SORTED_SEARCH_RESULTS";
