export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const RESET_SEARCH_RESULTS = "RESET_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS_SUCCESS = "SEARCH_RESULTS_LOADED";
export const SET_SEARCH_RESULTS_FAILURE = "SET_SEARCH_RESULTS_FAILURE";
export const SORT_BY = "SORT_BY";
